import type { Metadata } from "next"
import { type_second } from "@/functions/fonts"

import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${type_second.variable}`}>{children}</body>
    </html>
  )
}
